config/routes.rb
Rails.application.routes.draw do
  get 'lectures/new'

  get 'lectures/show'

  get 'lectures/:course_id' => 'lectures#show_course_lectures'

 get 'lectures/:lecture_id/clear_spam'=> 'lectures#clear_spams'

  post 'lectures/:lecture_id/like' => 'lectures#like'
  post 'lectures/:lecture_id/unlike' => 'lectures#unlike'
  post 'lectures/:lecture_id/spam' => 'lectures#spam'
  post 'lectures/:lecture_id/unspam' => 'lectures#unspam'

  get 'lectures/download'

  mount Ckeditor::Engine => '/ckeditor'
  get 'courses/index'

  get 'courses/new'

  get 'home/index'

  post 'comments/create'
  get 'comments/index'
  post 'comments/update'
  post 'comments/destroy'

  devise_for :users, controllers: { sessions: "users/sessions" , registrations: "users/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#index'
  resources :courses
  resources :lectures

end

app/models/lecture.rb
class Lecture < ActiveRecord::Base

  belongs_to :user
  belongs_to :course
  has_many :comments

  validates :title , :presence => true , length: { minimum: 3 , maximum: 30}
  validates :content , :presence => true
  validates :course_id , :presence  => true
  mount_uploader :image, LectureImagesUploader
  mount_uploader :attachement, LectureAttachementsUploader

  acts_as_votable
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :authenticate_user! , only: [:new,:create,:update,:edit,:clear_spams,:like,:unlike,:spam,:unspam]
  def new

    if current_user.is_instructor

      @lecture = Lecture.new
    else

      redirect_to courses_index_path
    end



  end

  def create
    if !current_user.is_instructor
      redirect_to courses_index_path
    end
    @lecture = Lecture.new(lecture_params)
    @lecture.user_id = current_user.id

    if @lecture.save

      redirect_to courses_index_path
    else
      @lecture.errors.messages[:course_id]=["Must Be Created First !!!!!!!!!!!!!!!!"]
      render 'new'
    end
  end

  def show
    lecture_id = params[:lecture_id]
    @lecture =Lecture.find_by(:id => lecture_id)

    if @lecture.find_votes_for(:vote_scope => 'spam').size >= 2

      render 'spamed_page'

    end

  end

  def update
    @lecture = Lecture.find_by(:id => params[:id])

    if @lecture.update_attributes(update_params)
      redirect_to courses_index_path
    else
      render 'edit'
    end
  end

  def edit
    @lecture =Lecture.find_by(:id => params[:id])
    if @lecture.user != current_user

      redirect_to courses_index_path
    end

  end

  def destroy

  end

  def show_course_lectures

    course_id = params[:course_id]
    @course_title = Course.find_by(:id => course_id).title
    @lectures = Lecture.where(:course_id => course_id)
  end



  def like
    @lecture = Lecture.find_by(:id => params[:lecture_id])
    if current_user.likes @lecture
      render :json => true
    else
      render :json => false
    end
  end

  def unlike
    @lecture = Lecture.find_by(:id => params[:lecture_id])
   if current_user.dislikes @lecture

     render :json => true
   else
     render :json => false
   end
  end


  def spam
    @lecture = Lecture.find_by(:id => params[:lecture_id])
  if   current_user.likes @lecture ,:vote_scope => 'spam'
    render :json => true
  else
    render :json => false

  end
  end

  def unspam
    @lecture = Lecture.find_by(:id => params[:lecture_id])
  if   current_user.dislikes @lecture ,:vote_scope => 'spam'
    render :json => true
  else
    render :json => false

  end
  end

  def spamed_page

  end


  def download
    my_file = params[:file]
    send_file my_file
  end

  def clear_spams

    lecture =Lecture.find_by(id: params[:lecture_id])
    @votes = lecture.find_votes_for(:vote_scope => 'spam')

    @votes.each do |vote|

      vote.destroy()
    end
    redirect_to controller: 'lectures', action: 'show', lecture_id: params[:lecture_id]

  end

  private
  def lecture_params

    params.require(:lecture).permit(:title,:content,:image,:course_id,:attachement);
  end


  def update_params
    params.require(:lecture).permit(:title,:content,:image,:attachement)
  end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/create.html.erb
<h1>Lectures#create</h1>
<p>Find me in app/views/lectures/create.html.erb</p>

<%= debug(params) %>

app/views/lectures/destroy.html.erb
<h1>Lectures#destroy</h1>
<p>Find me in app/views/lectures/destroy.html.erb</p>

app/views/lectures/edit.html.erb
<section id="contact">
  <div class="col-md-12 col-sm-6 col-xs-12">
    <div class="contact-right wow fadeInRight">
      <h1>Edit Lecture</h1>

      <%= form_for(@lecture,class: 'contact-form') do |f|%>


          <ul>
            <% @lecture.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end%>
          </ul>

          <hr>

          <div class="form-group">
            <%= f.label :title %><br />
            <%= f.text_field :title,class: 'form-control' ,autofocus: true %>
          </div>



          <div class="form-group">
            <%= f.label :content %><br />
            <%= f.cktext_area :content,class: 'form-control'  %>
          </div>


          <div class="form-group">
            <%= f.label :image , "Upload a Lecture Image" %><br />
            <%= f.file_field :image,class: 'form-control' %>
          </div>


          <div class="form-group">
            <%= f.label :attachement, "Upload Attachements" %><br />
            <%= f.file_field :attachement ,class: 'form-control' %>
          </div>


          <%= f.submit "Edit Lecture" ,class: 'btn btn-info' %>

      <% end %>

    </div>
  </div>
</section>

app/views/lectures/new.html.erb
<section id="contact">
  <div class="col-md-12 col-sm-6 col-xs-12">
    <div class="contact-right wow fadeInRight">

      <h1>Create A Lecture</h1>
      <%= form_for(@lecture,class: 'contact-form') do |f|%>

          <ul>
            <% @lecture.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end%>
          </ul>

            <hr>
          <div class="form-group">
            <%= f.label :course_id , 'Choose A Course' %><br />

            <%= collection_select(:lecture,:course_id,current_user.courses,:id,:title) %>

          </div>

          <div class="form-group">
            <%= f.label :title %><br />
            <%= f.text_field :title,class: 'form-control' ,autofocus: true %>
          </div>



          <div class="form-group">
            <%= f.label :content %><br />
            <%= f.cktext_area :content,class: 'form-control'  %>
          </div>


          <div class="form-group">
            <%= f.label :image , "Upload a Lecture Image" %><br />
            <%= f.file_field :image,class: 'form-control' %>
          </div>


          <div class="form-group">
            <%= f.label :attachement, "Upload Attachements" %><br />
            <%= f.file_field :attachement ,class: 'form-control' %>
          </div>


          <%= f.submit "Create Lecture" ,class: 'btn btn-info' %>

      <% end %>

        </div>
    </div>
  </section>

app/views/lectures/show.html.erb
<!-- Start blog section -->
<section id="blog">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="blog-area">
          <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
              <div class="blog-left blog-details">
                <!-- Start single blog post -->
                <article class="single-from-blog">
                  <div class="blog-title">
                    <% if current_user %>


                        <% if current_user.voted_up_on? @lecture %>
                            <input id="unlike" type="button" value="UnLike" class="btn btn-warning">
                            <input style="display: none" id="like" type="button" value="Like" class="btn btn-primary">
                            <% else %>
                            <input id="like" type="button" value="Like" class="btn btn-primary">
                            <input style="display:none" id="unlike" type="button" value="UnLike" class="btn btn-warning">
                        <% end %>


                        <% if current_user.voted_up_on? @lecture ,:vote_scope => 'spam' %>
                            <input id="unspam" type="button" value="UnSpam" class="btn btn-success">
                            <input style="display: none" id="spam" type="button" value="Mark As Spam" class="btn btn-danger">
                        <% else %>
                            <input id="spam" type="button" value="Mark As Spam" class="btn btn-danger">
                            <input style="display: none" id="unspam" type="button" value="UnSpam" class="btn btn-success">
                        <% end %>




                        <% end %>

                    <% if @lecture.attachement.file %>
                    <%= link_to "Download Attachement ", lectures_download_path(:file => @lecture.attachement.file.path),class: 'btn btn-default' %>
                        <% end %>

                    <h2><%= @lecture.title %></h2>

                  </div>
                  <figure>
                    <%= image_tag(@lecture.image)%>
                  </figure>
                  <div class="blog-details-content">



                  <%=@lecture.content.html_safe %>
                  </div>
                </article>
                <div   style="  font-size: 20px;" id ='comments-container' >


                </div>
                <!-- End single blog post -->
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End blog section -->


<script>
  var like = $('#like');
  var unlike = $('#unlike');
  var spam = $('#spam');
  var unspam = $('#unspam');

  var lecture_id = <%= @lecture.id %>

like.on('click',like_func);
unlike.on('click',unlike_func);
spam.on('click',spam_func);
unspam.on('click',unspam_func);


function like_func () {
  $.ajax({url:'/lectures/'+lecture_id+'/like',method:'post',success:success});
  function success(respond){

   if (respond) {
     unlike.show();
     like.hide();
   }
    else
       alert('Some Thing Went Wrong Try Again');
  }

}

function unlike_func () {
    $.ajax({url:'/lectures/'+lecture_id+'/unlike',method:'post',success:success});

  function success(respond){

    if (respond) {
      like.show();
      unlike.hide();
    }
    else
      alert('Some Thing Went Wrong Try Again');
  }

}

function spam_func() {
  $.ajax({url:'/lectures/'+lecture_id+'/spam',method:'post',success:success});

  function success(respond){

    if (respond) {
      unspam.show();
      spam.hide();
    }
    else
      alert('Some Thing Went Wrong Try Again');
  }

}

function unspam_func () {
  $.ajax({url:'/lectures/'+lecture_id+'/unspam',method:'post',success:success});

  function success(respond){

    if (respond) {
      spam.show();
      unspam.hide();
    }
    else
      alert('Some Thing Went Wrong Try Again');
  }


}

  <%
   @user_image = " "
    @user_name = " "
    @read_only = "true"
    @user_id = "0"
   %>

  <% if current_user %>
  <%
      @user_image = current_user.avatar
      @user_name = current_user.name
      @read_only = "false"
      @user_id = current_user.id
  %>
  <% end%>
  $("#comments-container").comments({
    profilePictureURL:' <%= @user_image %>',
    newestText: '',
    oldestText: '',

    popularText: '',
    sendText: 'Comment',

    editText: 'Modify',
    youText: '<%=@user_name%>',
    highlightColor: 'green',
    enableReplying: false,
    enableUpvoting: false,
    postCommentOnEnter: true,
    roundProfilePictures:true,
    readOnly:<%= @read_only %>,

    getComments: function(success, error) {

      $.ajax({
        type: 'get',
        url: '/comments/index',
        data: {'lecture_id':lecture_id,'user_id':<%= @user_id %>}
        ,
        success: function(commentsArray) {




          success(commentsArray)
        }

      });

    },


    postComment: function(commentJSON, success) {

      commentJSON.id= <%= @user_id %>;
      commentJSON.parent=lecture_id;

      $.ajax({
        type: 'post',
        url: '/comments/create',
        data: commentJSON,
        success: function(comment) {

          success(comment)
        }

      });
    },
    putComment: function(commentJSON, success ) {

      $.ajax({
        type: 'post',
        url: '/comments/update' ,
        data: commentJSON,
        success: function(comment) {

          success(comment);
        }

      });
    },

    deleteComment: function(commentJSON, success, error) {
      $.ajax({
        type: 'post',
        url: '/comments/destroy',
        data: commentJSON,
        success:success,
        error: error
      });
    }


  });




</script>

app/views/lectures/show_course_lectures.html.erb
<section id="blog-banner">
  <%=image_tag 'blog-banner.jpg' %>
  <div class="blog-overlay">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="blog-banner-area">
            <h2><%= @course_title %></h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<% if @lectures.count != 0 %>
<section id="blog">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="blog-area">
          <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
              <div class="blog-left blog-archive">


                <% @lectures.each do |lecture|%>
                <article class="single-from-blog">
                <figure>
                  <%= link_to(image_tag(lecture.image),{controller: 'lectures',action: 'show',:lecture_id => lecture.id}) %>
                </figure>
                <div class="blog-title">
                  <h2><%= link_to(lecture.title,{controller: 'lectures',action: 'show',:lecture_id => lecture.id})%></h2>

                </div>

                <div class="blog-footer">
               <span class="fa fa-comment"><%=lecture.comments.count %> Comments </span>
                   <span class="fa fa-thumbs-o-up"><%= lecture.get_likes.size %> Likes</span>
                </div>

                  <% if current_user %>
                      <% if lecture.user_id == current_user.id %>

                  <%=link_to "Edit Lecture",edit_lecture_path(lecture.id),class: 'btn btn-info',data: { 'no-turbolink'=>true} %>
                            <% if lecture.find_votes_for(:vote_scope => 'spam').size >= 2 %>
                              <%= link_to "Clear All Spams",{controller: 'lectures',action: 'clear_spams',:lecture_id=>lecture.id},class: 'btn btn-success' %>
                          <% end %>
                          <% end %>
                  <% end %>
                </article>

                <% end %>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>




<% else %>

    <h1> No Lectures Yet For This Course Visit Us later</h1>
<% end %>

app/views/lectures/spamed_page.html.erb
<section id="error-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="error-page-area">
          <div class="error-no-area">
            <div class="error-no">
              <h2>Spammed</h2>
              <p>Sorry</p>
            </div>
          </div>
        </div>
        <div class="error-message">
          <h4>Woops! This Lecture Is Spammed </h4>
          <p>Sorry, other users has spammed this lecture Return to our <%= link_to "Home page",root_path %>.</p>
        </div>
      </div>
    </div>
  </div>
</section>