config/routes.rb
Rails.application.routes.draw do
  get 'lectures/new'

  get 'lectures/show'

  get 'lectures/:course_id' => 'lectures#show_course_lectures'

 get 'lectures/:lecture_id/clear_spam'=> 'lectures#clear_spams'

  post 'lectures/:lecture_id/like' => 'lectures#like'
  post 'lectures/:lecture_id/unlike' => 'lectures#unlike'
  post 'lectures/:lecture_id/spam' => 'lectures#spam'
  post 'lectures/:lecture_id/unspam' => 'lectures#unspam'

  get 'lectures/download'

  mount Ckeditor::Engine => '/ckeditor'
  get 'courses/index'

  get 'courses/new'

  get 'home/index'

  post 'comments/create'
  get 'comments/index'
  post 'comments/update'
  post 'comments/destroy'

  devise_for :users, controllers: { sessions: "users/sessions" , registrations: "users/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#index'
  resources :courses
  resources :lectures

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleMooc</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
</head>
<body>
<div id="preloader">
  <div class="loader">&nbsp;</div>
</div>

<!-- SCROLL TOP BUTTON -->
<a class="scrollToTop" href="#"><i class="fa fa-chevron-up"></i></a>
<!-- END SCROLL TOP BUTTON -->

<!-- Start menu section -->
<section id="menu-area">
  <nav class="navbar navbar-default " role="navigation">
    <div class="container">
      <div class="navbar-header">
        <!-- FOR MOBILE VIEW COLLAPSED BUTTON -->
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- LOGO -->

      <%=  image_tag'logo.jpg' ,class: 'navbar-brand logo' %>

      </div>
      <div id="navbar" class="navbar-collapse collapse">

        <ul id="top-menu" class="nav navbar-nav main-nav menu-scroll">
          <% if user_signed_in? %>

            <%= current_user.name %>
              <%= image_tag current_user.avatar  , style: 'width:60px; height:60px; border-radius: 50%;'%>
              <% end %>
          <li ><%= link_to "home", root_path %> </li>



          <li><%= link_to "Courses" , courses_index_path %></li>

          <% if user_signed_in? %>

              <% if current_user.is_instructor == true%>
                  <li><%= link_to "New Course" , courses_new_path %></li>
                  <li><%= link_to "New Lecture" , lectures_new_path ,data: { 'no-turbolink'=>true} %></li>
              <% end %>

              <li><%= link_to "Update Avatar" , edit_user_registration_path%></li>
              <li ><%= link_to "logout" , destroy_user_session_path , :method => :delete %></li>

              <% else %>
              <li><%= link_to "SingUp/Login" , new_user_session_path  %></li>

          <% end %>


        </ul>
      </div><!--/.nav-collapse -->

    </div>
  </nav>
</section>
<!-- End menu section -->

<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
<% end %>
<%= yield %>




<!-- Start Footer -->
<footer id="footer">
  <div class="footer-top">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="footer-top-area">
            <%=  image_tag'logo.jpg' ,class: 'navbar-brand logo' %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="footer-bottom">
    <p>Developed by Te7a</p>
  </div>
</footer>
<!-- End Footer -->


<script>
  $('.loader').fadeOut(); // will first fade out the loading animation
  $('#preloader').delay(100).fadeOut('slow'); // will fade out the white DIV that covers the website.
  $('body').delay(100).css({'overflow':'visible'});
</script>
</body>
</html>